/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_urbanojvr_jniexample_JavaCalculator */

#ifndef _Included_com_urbanojvr_jniexample_JavaCalculator
#define _Included_com_urbanojvr_jniexample_JavaCalculator
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_urbanojvr_jniexample_JavaCalculator
 * Method:    sum
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_urbanojvr_jniexample_JavaCalculator_sum
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     com_urbanojvr_jniexample_JavaCalculator
 * Method:    multiply
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_urbanojvr_jniexample_JavaCalculator_multiply
  (JNIEnv *, jobject, jint, jint);

JNIEXPORT jstring JNICALL Java_com_urbanojvr_jniexample_JavaCalculator_sayHello
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
